{ config, pkgs, ... }: 

{
  # Add packages to the system environment
  environment.systemPackages = with pkgs; [
    bitwarden
    git
    python312
    btrfs-progs
    appimage-run
    papirus-icon-theme
    gnome.dconf-editor
    libreoffice-qt
    gnome.gnome-tweaks
    spotify
    tailscale
    vlc
    gimp
    wget
    zettlr
    winetricks
    wine-staging
    pavucontrol
    fluffychat
    distrobox
    geany
    thunderbird
    ntfs3g
    appimage-run
    firefox
    flatpak
    discord
    kopia
    tdesktop
    screen
    nodejs
    pipx
    ncdu
    python311Packages.pip
    caffeine-ng
    php
    adapta-gtk-theme
    mlocate
    yt-dlp
    pamixer
    gthumb
    unzip
    gnome.file-roller
    lxrandr
    pinta
    okular
    plex-media-player
    virt-manager
  ];
}
